### ISSUE TITLE
Delay en que aparezca "BlueLemons"

### ISSUE THREAD

**Issue by jjconti** [bluelemons/bluelemons.github.io#2]
Cuando entras al sitio, el texto "BlueLemons" del principio tarda en aparecer un segundo más que el resto del sitio. Es a propósito?

**Comment by eloyesp** [comment]
no es a propósito, es un tema del tiempo de carga de la fuente... no tengo mucha idea de como solucionarlo, la mejor solución me suena que sería embeber la fuente en el 'css' o darle una fuente anterior para que ponga mientras carga.

Gracias por avisar.
